apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: myapp
        image: myapp:blue
        ports:
        - containerPort: 80
