apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: jenkins
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: myapp
    version: blue   # Initially route to blue
